### ISSUE TITLE
Orphan Items / Event Objects ohne Events

### ISSUE THREAD

**Issue by ghost** [OKTOTV/RENT3#17]
Impossible to invoke a method ("state") on a NULL variable ("") in OktolabRentBundle:Event/Event:_event_status_lozenge.html.twig at line 1
500 Internal Server Error - Twig_Error_Runtime

Robin weiss Bescheid

**Comment by SrgSteak** [comment]
im template berücksichtigen

**Comment by ghost** [comment]
Danke! :-)
